---
- name: Ajoute le dépôt de K3s (get.k3s.io) pour tous les nœuds
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Attendre que le service k3s soit actif (master)
  systemd:
    name: k3s
    state: started
    enabled: yes
  when: inventory_hostname in groups['k3s_master']

- name: Attendre que le service k3s-agent soit actif (agents)
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
  when: inventory_hostname in groups['k3s_nodes']
