---
- name: Déploiement du master K3s
  hosts: k3s_master
  become: yes
  roles:
    - k3s

- name: Déploiement des agents K3s
  hosts: k3s_nodes
  become: yes
  roles:
    - k3s
- name: Installation du NFS (serveur + clients)
  hosts: all
  become: yes
  roles:
    - nfs

- name: Déploiement de WordPress + MySQL
  hosts: admin-master
  become: yes
  roles:
    - role: wordpress
      tags: wordpress
